---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: fiatlux
spec:
  encryptedData:
    token: AgCvzbE5UJN3AvvPk07TzyoBsP+shWoGWKSMotEahXiv0HLVqPY+RET+nse2LBmK8vynp2CpY3FaeibIMyxMSltapGFGSeIBna4sn5CDCUXToBomzFFlfTSCzjaOOcPuTRh02550qS4/Q3Jguku+4VOWMu77/7Obj5Q8jgGieyi6+LUmWpOqKt25jlzz7MQcA0C1/ysqndJjz+YDQbXT94cGnCtCmzISAM+RucUv4KbUNg0G7GCD0f3kQR/+jPngEFeYVT1X2EF1Maq1gvUwNUiu8XWhfr82VIpyj9r92Zp4Mhm6LkWa0zRlZpO6+egQinQDtdPQdoTHqJYv6Vzls/YNBVaOe+8TM5xsAEXrKUYX/7AKYi/aUvMKjmOo9V9BgySQM31/3JwoNvJXe3oofUHOIzWYbq/MX2yIvSw9Q5sxV7Ng7Qf9cgsAR9aySMHWsjvY/gQvcb5KCbggXP3uJh84WhoUAExgePQb6Uw1IRHRdbufGrmTiyro9kBazH2gL2TiV3m1uBw7i+ekREDSMHwXFfL2bpvBmoy05KtPVHB2bjw6v4QsE2HcS90AqUSCUhgPnxAkhK650w763Nd/lkjKuutfRSfVHfeVKOVn9gBqXnXfWZJt1bnJHNe1yCXWTS1JtUENErZo8kgQtr4OxgSPjhsGUiP+cjcsAp6TmsfUtCEoVHqB0MHY16anMc70LxeE+v7NRtuaWtntse7yJwTmTZ8ImAcGD7M69Fk8OXr93iCn/CYIpxTgi6jU3aLai1PC37D+Qd3qaju9PbGPVYvfAQ65hibswwq5WiROzcAiT4skle9dhva6JbdikiLZo+Tjm6shw5fzhlzJx9vBSQz3SwtUNpCjR7UfxFwHMzqH0dQp5oq3gBRbI/tnKXDFCEWzImNCNIDlhRlk56O0chIy5/T5cj707fhIVF5DbFClKfbAuYM=
  template:
    metadata:
      name: cloudflared-token
      namespace: fiatlux
