---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: fiatlux
spec:
  encryptedData:
    token: AgAm//d0bvUOHQ5ctT6TmTHvGqEzSbxcd7jyHr6szs4DWTyabT90qmSXJRiWLr8fNhj+TeCsgQnkjiGuC0AV4MxKobkzZi1ERSf3q54WMDCvgeH/6QEiI6+RsslvDzivcU9NQoSESNrqMqAXNB7iW4/+6ZXeNB8NoenrOm8Pdxp7N93vL1uZCif8rdUMBSQqglvuQ8tSLcJ5C94BO/Y426spBM2nQQx7Ydc76EVbUv9yzqLMK39DouAAxoHhvHG4u37esXKDmI0PTw4nEsVGRZWDYTqsUlpf+an2Tinen9iIJVqQD7RWcITADrFHqmdxSeZ0hmTyxVuZKYO5+XBufO5Jub9YCIAklMU+i+8Y18VDQv0+9yP0UhsV4g060MSuXvmI0vqt/tY5VaE6liu6PFy3+aGO4iBAzFrGhCWUiCWokKoe8ZBW50fjS6erJBOAaf8tmaNkQ4w0qTIVbKUP6xQOfqYwq3LjvMzEEfDPxCN+3EoaBxvb6568dz+GWDgYnAuKp3ySUv8uoGDjcnon4qZwd6dNa9L99+vj7+y0qjkA9PuoRo82iLQToSqkvB+5zlwinfj8IVJI1hXtAp1LnQ5NsBFNtukNc2qCyQ695PM5t0SyCkl1EjpFMV2TE4korQtKl9dMM6uxeRCnfVSvYMMhDNzvA7FSfUQrLQPyR1fzEaecC3owmYMOuzd5xPQmsmQsaw1i89qyc6SFtNLL45NtdY4ZuZGif9gT8QKgk0nnKL2Gg1dc8tGe0dSzh34gyYUJ51bAOzbYaxFuCWpkiyconSNpppNg7Yv0I6yi+Z5GPkIvrjm6gCd9E4MsSyPwwU9MXxch7zHW7qLFOkgsTJnGbAD6CNMHIR9BAIZTi++dR/5pybCL+IKYaZWE8nfeOwLQ+4ObmgtBc6cHp9zrnJHeW7n27wev4z7DjXp1HYOksHXCakw=
  template:
    metadata:
      name: cloudflared-token
      namespace: fiatlux
