---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: unum
spec:
  encryptedData:
    token: AgAMIVz6Nht+xNzCHoH0vz9gtN+Ij2rlDoixk1o3oxJNqyMLWmPsF8rqwSBqjCOHDSLo/YxSsttOrsMO4bRgea143JM8DXF4Y82hhob8PHsk1YMsH2kqMGOm9sZqwOllsGWYhKLtCO30G4dvG+30VFfEinQlmRxgKDRV1iJmBZdee1Kixjy3WMGOKSv27l6J3qbhtGoCkbhoa9uz9K75zh5dje+OBnEZDp9XreruTIs4fhTJRTr3ioXkbyNBEmp2Wo81dAPQKcuosl78GXyd4oEDwMlBN5wbeLOS9bqeJemnSdEly/yaVyYPywDRRX7D4gCobe9dhtzXfue98nsyjkUB32wG+2Fk/rJ2jKdGS3qD0PpEbi00wAiuKa1mDM8ayYc7e/nJX3Q6LZ6HzPoiqVeuBKBuJONfZMW5uGDAT7bHXKu6zB8ZreAn0vtD6wPYxqqBd72HOVBhaqiJEjTYBXApWUBF/7YMyfnpq7tw3v9C1HXaU8m2rVLxHxz/fazgPQCfLBb5OQQiJlJDtKg52MRuzfXNl4LnHwlTGtqwpkGlMYWpk3xFsXY4xjY8UqUkFC5zuoDx4JqmOWWpLP+gDIJetl4cd2DayKCE61K5Em8vyonzlgRwM6Ws49gBiu2ITHq2SHvacSSo0WAn46oYLYXQJmYorl1tcrbiyACAZqr7lr0591OheWIPQK78BskApYlXdwlhTdryy4wnLLvo1Wn9SsXaSvZjN03Lw1UnL9dKHH1u20L7u9zyDXi2919wvyIW+Vy7uTvG4+EQjcLnW5pkf59QBEpU9Ey4fRBSfTSqJVzvf18Y7ExYg4k0Ojgh5rOUeMgMVf4qEsrUDZ6GfqIuVW0fkEBajz2QP+4xw8n+Wt5dOCgq2q59JRCjiX7vATJdJKausSAIr9sCHKYfG7CNf5qd6c1zywGmgewxiy4CnSGmDFE=
  template:
    metadata:
      name: cloudflared-token
      namespace: unum
