---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: unum
spec:
  encryptedData:
    token: AgBAK+VzqSV/lL/OMXsIZU6rijMIhUDvr5XhfojJzzwotG+c5TX25UKFLN+O9dkyNutTkWCeRPDigio64UsKONyGczw8ij88bmDT0ZKYf8PvVl2y2EbBxOotnSri0mQCF9wV4Me3TyvVLEtz5CZ/zUc1NlvVUfGiTBwI/RlZIDjztLRe9sIGXvhe6GoRIDkuUw4NA/+zsdg1QiQjs+D3yfVzAWn6z6sq9cdREBM0IHpeU3Vu4BOJex4EOSp+9FXKz55VAWNMd33Vty7ReQzmsY/QZ0xHRHyXmaeZhrXY6ZiIJ4hS38LJyNRzk+nCSm8z2ezaZSbjPR9Y9GuzpRrZSsBrl0OsYGSDTs3EN3BVGCIvFQVBeEeoK+rTsHAxSEsQMkvGEqOBi1pprqFCOH9hpSAF8V3KrLdWlsU3WYA3ThvbrYZyFS+DgzJOv//nHkQR/ouFLL50RBFUrwFGm5DnC+Qc69LtRYw/BPsmsUH7cuA0p4F4M9ntLstcHZlELFlvf19+II0Z+aHwhXdriH6kBNqbjdDP1YMhankFBgljOy2jIMGtQBHQGo4GoearI+HnjsWqa6W68cy1yIKfzaXPB5wimNrCdI77JRyUUG9tvx71DhTFLO0wdVSArwXMS6UhGaMs5XR1L+llm9v44RnxFr9QpAo/hJPjWsnHXtLtXUTtewiWz3mfMkdJOkbGCaCP5n9GolnD/MJg8W47OOvu6Dfp/vh6TunTdah3EefsCGi4UAhBtXBfRZrVkUquvX1FP8aquSHtLC5Ub1Y7B11/3HJ7tEZ3ZFqrskg27DbBQnuCDolL8vax5KHpQ5QHDNFgxWfS373VQI9wZtolkK9qeLCwprPjuVLEj19M5zpfmMR67vGDgCTvCT9vlD2xp4qP/EpuW9N1kW8k83wrQhyT2H4yMSx+8APJ5YpY/Lmwdsv9jAP5de8=
  template:
    metadata:
      name: cloudflared-token
      namespace: unum
