---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: platform
spec:
  encryptedData:
    password: AgBFTSstrgRWq4ro2q5h7QY0l2jj6sC20RzwcBIP881qCj5gBx1H6iHWCLHQ5rZ1Z3gUWmE19PCjlp18nQ5STSQbfZXV8l8M/KswG+/aC1BwsbOwQb2SrQwrnw3WBvpS0nskvUjF45ffld74vkHeXEq14w24HIrNUqe4O6Ulh8nNYvyPJ0xraNmpSdbqbL9Ks7zQDRRjF+YAUAAn1rwKTkSDr6dj+mbQt7+rq5kMyQTnd7/ppgATjcDaz2ThKNPbXSwmmq7M0+JBOhJ65trkcfCwB3o0pNdk3BoFcTuJdx5KNFMd5PiYOedIvhVbBzkzBuBJCxoMFPdGtseNDkR7j1XXMsjQPP6ZpIofYDpckxxeaIqJScC+rA9VJv3U4cuZZgtPwfDKScwEPKI7j6snbjVBTu+MIREVPkJe1Qjw10sb1jiRUeWfeGpre2OV7PtDr1wFOJ1fV/DrNwDv+hYcS+jIpzbX8GjTFq9bBPuXWlclST4qbzi+FInZ2XSBsJzI72odVIIt+9giBp7XhVP2EkM27lb9tazFfz5fHWaG2GpNWsTi+/FARTK1x+PXMiSUiQnrXhSTJOowcSj2vo3rrlMTtdZD588WX3Eks8ykAKO3yLvVOmmzsXRB7F2A0KyW7nceT+XdY5FZuJtWqrT4tiZdyusi1r7a3n8AXXVTdT1cmxZPIiHpQwuwxhANMT+wFkxM4X5La3yH/VhOGmZ3AMx94Wc45XeWnSNZxfHL+LG6J1+DZ+YTAiQp0RGq
  template:
    metadata:
      name: postgres-secret
      namespace: platform
