---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: platform
spec:
  encryptedData:
    password: AgAKfyC8Bt+5h9UpxN3VdILt5iaayEWoszFNXqBIt9sctmW392wNHNkCkPt4/lIgZlaex+c/EQIhXfr5N4g67oddiI6O6bz7DLRafSoCQ9vWwCab1WtHvl6WEDijbWy1llRBcyh1mxPorKI4jWcvxDxcBVda/1JvgjOvGMjcT6+VuXmS8AvNUGHw/EabbXhfGCpLyQRwvuHyEtTzR1riFfjxcNtUrsgH1I5Va5MDigYNE5zYv143/Ybxe5Cfot+8fEETeOYjiCEg0GVuBZngygAAI6nzqlIzhQHbAktrQT09gDQTEkdJ7CvuWiCLdQvN7i2EPrqezAI/c4Prsh3gU/xhmSFXevwjnmqrdJ0F4Xh1sFcZ4t+Oyn7BxZpR7cmNs/deAe78A2wyZsVhHo23qht+RF/GiV7GAnjcWESKHrHrseJN9pwxPH8Qk18s1KtcmNAvQ7vmwfrvY5ZRKWNPQ/6WDIHeo7wXcl6S/g/i2Nmm4rgpbBI+wAa8lOnXro8mIm6GTL1HnBp5NObNowaJOIegKNIgKq6OC4l/2X0uLEv2NpGcJqPmXOG9KxAzia2DCy0WfC3kbcg9MqXuc4y5/1oY7+Jid21U00RhgOd+YfYeKZWDYKIHBRR7YCHsJ0FSsl/+uaSRorS/Rx9sQy3nADKmA5+bx0eAs2MoP40gmXnZMNlgOOf2SZKRXbl1wA+nIJhKlwZnj6D0NhZ8jQRGiZMrxzGOa7N9FhVh+kMN1EsuRtBtDhtUCJIFajd4
  template:
    metadata:
      name: postgres-secret
      namespace: platform
