---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: otel-collector-secret
  namespace: unum
spec:
  encryptedData:
    auth-token: AgC1ALPh+kFOw0KnuanY18d957kASQV/cdGR1ByckoyYggP5HRrxzRk+Eyn8ADd0UsPJ1qBuyun16G0WSgrd8bvCdEfOZ4mm0WfoWWX54YMJRpRSKJblrQPnc1J2cVU3kEx5DTqqFNmYw53bqU3Vhq+mW3uDKU/O7cl7pgJ7tc/6ClGlYhh9+g1b2HPjDkXm+CJO7+IfFr0ex9vvulH1ydDn1xZ7C9tQfDUoIQZrzECr78gjITqbWKICFmlbze7MWP4nonanS5AdvFGKNYiAe6gUMeorIQSGc6t2DB1zY8716TfJdU+KzaRmIhlzcpLMtX2OABlRGpC6ry2nkyhAkPjVe9jIKY3QgdQitX98SDGS2SVBMAaMsrjDS1Xsu6ZsrPwvXuH1ePBoCnJ4eN7a+jQyfzzxK0HGdXrfFhfrh7LW6Z+tVfaHHjEvvVDY+rFNg8vab3A+o3wRisR3piXLKM1iPhATvr0kTIe/Coh/dOavQSfnSOQieeFVSexRKu+CmAMY1l/frF4u/1r/3wR3axtwS0p01MDM+48igIjTyYSmkagDNacc99rC7pm3WEaUW7PbpUNvsjJlyMIaeAiAcABWolLUBidPU6D53YXlhcp/aSYsOnbqeIqazVDBlq8gDCva8I/F/tj8NBLcTEmPGdpMtDwasfT94CiQmJlAxvSvp8s5rEhgH6kmWG51QbCD/aaW5U/WDcpDQGYPxO6czb4tucJ31x/IZdh3OdSiNkFnbgWMbT9Xn2s0Ls8Ytu9upmGPkURTLi0XimkNpRiPi5t3
  template:
    metadata:
      name: otel-collector-secret
      namespace: unum
