---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: otel-collector-secret
  namespace: unum
spec:
  encryptedData:
    auth-token: AgBQ2Yp+BopCxBGopt3G3d4GDXOn4rFQFuxkW7+On2MxT6kMuHON859ng9zTslkEj3O+wIlE3U0+T/g4bEdm9gPLxa27hYYZpgddw5/Wp7d2t6KQ6V99V8aKVz9rcRIeILLbLhClXhSLf065Eey4bbYgtmdLUgAdF20TuyRbp2OlCWpV877aKtL5BxtjfVdwDwJs9oaWquuOdwnb9SMJJ9RROKblVmfeTrOhOsdRdYErouSZcigwNKsKoRyJn6LuIDyCHDqoy7AlOiw6FxY4Xo3DrNdatU165u4OXedh0QV+2rPyFEVrhFqPa8kyIWAegawEapKcm0GbuX7mB4H9kU2WpMTzIrSahB33x3NfiArkFNWTqFJBvrgw7ZHCTrMZ3+iQZeN6jf0d4V0OSiNc4FPvoTAW8CgLgxUgD4LzJxWZp7ZOBBxZXpKitILTuIGTb04Ckovwr98NBAcAk/bZXPGof8vn119PZx5gn2YkZ6wfHO8zyO+KHiUNwMMZ5DQuSpmefIVm2009047mlokiy8/xak3ityij9/g0J8vdpL1Y6pcUujKaHtUjoXKfkSx2SAtKdlNKCMaq6JvG198hm0c+i9DyZP+ZYEo7fbmHr8Rzgu5fmbknBXrGx3eDYx4SI1JcILx+7bMUXkBSyOQ4mtbAldI+tzfLiEa745yBoa6lsho/QqByZkP3Y950Ugh5484bpwsc10I7bF1ygoX1OMN594NCIBfbjDWndNG5Q6VafvrB7z93rgw8FYaGgKeFuz4NyEkEKGVZSNnXQWCyZZnk
  template:
    metadata:
      name: otel-collector-secret
      namespace: unum
