---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: unum
spec:
  encryptedData:
    token: AgBpy7STXBcgjaG+bpHdraemVS/CBjpHMC2CbpLEGeotXhrNxDFUxy/wxOlji2w620K+4teJ7adl/gN19jZhmK0w335h27TU7aUwcr1d+BX9JSIFfqTunlb87R/Yppywk2hR29N6+fPNgUF+EATltxEsbtgMDOduE1rE11+LdBOJCJ1b3ywL0ZQwJKzFOX3vp8MSnWRNDUoQyGqr+x7Rj+Sd1NrEAmiE79Ryy1uLpR3IUlPqQZ8LTQQIeWcndqnT0z7hCtPmPxVqVONK1/dBUuJ23UWrEWxSWa6JGPuQTlU/wBPEh60fIawZ+IX4iql8Y1O57Z+uvD0IO1sYrZy6cllhlxvvonBuwpBc0lQmCPH0+BRpkIA/W3td4L3ifjGb9iPpjpi5RjHjzN8faJxgHMsRjaALAi+Xx2Q260O7w3wVTtOgPhLqQDMDEjEqNhPjWQ1zU9x+EdOMG9AObNxheutj7Dwr0HCk8s6/rHTJKZ8qq86h+HDpeHSJmpOyyqUbT0ntGmTNB+LnIozF5rilGp+Yn+H1M5pk0HSB/QQ8o/hwoKDkaT1x+VyI9XfpjlkCdwXk8yK+Ly/vJLD+OFVDipCLvMVW4yWc6RzDNxw0MB/GmOa+NFgd6+Uh6FHgL5AdGoCpbA0YyfpPpr0GOp/WUOJpZ414SyWnuwei9S16RtQM/BrOiVrUcgCxAjYfwLE+p3yuenemiH6Ns0J8aeZ2IZmX/21xNLqbvqwYGg/aioArZri89P74eqs1puryzldui8dhclECZuENFoE/Qtpprr8YVtC5JP0TQhyGpRzWAfeFQfay5aDSJcbCJAbvGXG41E44Y5tCww2wX7zcoyMk24GbAahZM/aKTOPjZqInsyJDR53p+KTYlpv3prtcHvB6Bm0wJyuPJxxiOGJHjnSPPcXbkFmEBFE8y6hqMn/ANk7c8zpNmkM=
  template:
    metadata:
      name: cloudflared-token
      namespace: unum
