---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: unum
spec:
  encryptedData:
    token: AgAT9IVz4ymLdITQkTBUNlGtF5qUjJSiNj7P69ORpBK8e6aj5WDfTwqeAzwkLK+kRO6vbxj6ZfqyDhE/oROmOkg5UnOxuFnrlEr31f55tJravFB1Nb9C4ON8RNb3kwFWQ2QvzFdp00cGqAswAvl/Def5e7X+6hZ9zidjUebfvGQxt0M0hSSzmWGh/alJcVV7EisH9LfeDB15LtKfu3ZB4taXibLS3cukMzrUo9zk8zLi0sbW/tCNyyrJ7zByQCXEFDei0OoILb5MNN19MwvLoNby4fHUUIMRgIPH16LbBUyyPPWk+8PDkGVuWvqQZN+s+oh+wueUOz2LTrYaBZdOuMv0g5h5uzZLGBO3LV9Yo8sicxzYHBo97kmOfstxAMBRYZw9C8gpVS+Os1tsyAy7/A5X8HnxP9Kc7RdyV0aW103mbJ1Pj1XWDuLAQuOuqNZmxk/zwGnH234l59S6fklWxuU6CDaKSOapEbMdJL9zh6mkCaVw5nM7WIc4X7Ktd0UMlo7f7rrrcuTMj60AueE8xm7B8gCIOdtSThEhvODMMJgGKr7DGzqRNnTTaRhVpThNviuXBMorgYnsC5aPCX0g2aRKQozj02lQeInk70HGKWl7HqHM0JFjACpEhmJMz9MzdRloLhdbyLJoxanMld6P9uimUkA74yqRDhJTx3sC2GC3w9CBAAgzDgWJr2q+MxTrdRFFOaYdqTzrFAajxpFrDv/9pTZISu1GKO98lk9QlEO3oA7aQ4P+PqrA24y3W9a+sLYY1Jl3TViuaBjS5tPVuh2ikV5ip2WnHQwOaAxZh1KGiLuJsCtn0YBPjayQQdAHbsn6M1iP/5IBg0XnW7OMOiiElIEchHDIaWzmnQVCcbJ4NQq3T0Slifkrxq8HhzlbzSIiFxyeBuQpUhjlT+Ul0nVkDrH1y54XWnUwJ9Elewa/yQg0dSk=
  template:
    metadata:
      name: cloudflared-token
      namespace: unum
