---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: unum
spec:
  encryptedData:
    admin-password: AgAbHJD1naFW/PcFdwyI9fHI0DgIwHt0S5HCChDrmFfqX2/r1DzU8hLhFhER0aowQj1XpRnWctTJXPIJGfflyMX+qMpyGQfusNeGoOcVd4vAgccXxEiIOexoKZSxCipvJk1VKdPQcjz54cj1xe7QdO7OtjlS0Ca9U2l5C6w0p42m5oXIAqunaIkqiaMoA9CkRkjZwqdtUzx+6W8W6IpviLgayXFeX6H8FnWJus9Myjr4j5cL9BAIR9hsNx4v9QFBzHZxQbVR/+auAw4gDGuDEFskBFPejiGCggecyGNrnf+x9s+ySiZCD26QrDhufCsr7NHvYNbFmquFIoN6z2GMc9HjlIFfpTEifJ+BMrWnj/6akoneR8AV5fbN64BwLjFVl1MCDlU8fh+ArxvxTXK9qvvBo+fA0bKI9AWR3DrA7Uk8aXaY5GbYaYCxPGQw+KdUtXot9G3CYPsM4/kI+f7/q1eMFwifat7oSKB/jnAfOz3ovPOzyxms76ulxiScUiuj7IiconXvhDSadZ+kaztlpNlXIv31/Ny7ifjSlEzgOU14fgKOcEYbHndatHSDVEozz/NuyYW5mV9XHNkpR30N6HKTxqG2X4XaILHTBDHnNeqyQBaB+U9cl9nA1gdz/sBSjqTppURKFKUiv4X1qz7bQ3oJKO5unb/MT89J5rjl7Vfm0NGpW79XJSNFJB+00vVM6jYLiTwiHD00ZFWxGJ6g1JNg0K+U4Z+xw6+f3ehrPh+M9/DYd2h4ZMbYKSGD
  template:
    metadata:
      name: grafana-secret
      namespace: unum
