---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: unum
spec:
  encryptedData:
    admin-password: AgCO6ocl23ctrNThv28zAjIfZcAJZCPHmwt3VnAU9z3t0DpmX+q80ix1dLCESFpW6ntXGPKGrxz3DxCjSnH/fPzr14t+Lu3XsvS+SWV6DQM60pXqZ2S4G1Ropa6VBwKjMakCOwnFJPaZcZ/t9xpaXSFkW+Xpwhlw2o9tOnaVuxzkY9U4nRt9iXDSMzQNP+a8WOcRfeb1Od9NUVvpcW+DAHyY3AOEGutFqkFWN7jOKlrHqObk/+4kvLTJ3JYneq5pVHFigfVul9V1I53GUxpu51qAP0PHATlT0aKtBLt48dLpxKDwRLcZg2EC/qE9UrdmAYhErATlGHOgrkLKETq52V5F7JHg/JEyXa1VhCC4h8xCnbSwSX/Il9+1E+y0Qb+xKLaOE30jryQY59WzEauzA4vKfYYCHuFtTEOdnPUbcV+A8wUyYZncWTmPPoLZFVTeHgYMWY+u2c+UN/gXWAXhDvp+3IyHsjRbFeXE/wnOQXLx1fghbAJFZAYUSSGC2ABxVvg8jMMOZ9Rujrxj9Oonzj66DF6e3AeEZtCMthkNOToIM/qzBd0HMqRQo8p/wUgLJldmyVKz0OoKymP/OLYNak86pCELyCW0IdHoWU0qodzg3WkYr4mCodFn049qM1iKGq08rm1BcCMB28eIuTmmKryxj9vZchBhR25ELS6qMp8GjVUcYhQkFKD+OysaZyq3M+TWo+hVWYqNVop2e3JC5QIPWBMML7qi/2gcMCEYnNA6EvdhgTa8uCbewpBLUQ==
  template:
    metadata:
      name: grafana-secret
      namespace: unum
