---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: platform
spec:
  encryptedData:
    token: AgB31JqzhAqwKVRHtd6ETpVR5Jjo+pIXdDyZp7TF3vhG6MNAuQS+UCgC1wjKm5FipLHyIYoy4sRa64evdIU0H9q2htJ7xmQwmd3/AQuoIwTpq0ha5DZOixAMivoq0FmRJvPbw9J07zy6dJiCfFcxlgyJU6cilfUpkIfb/uU/QjvXZjv7moyZGUWX2gxT7mmq9+i/fxQtVmfTP6QXfd/v6qKv3PHK8EX9f7hwryfqTu2kgMmhzDvNdFNRZU9oNrrOwkOtSjsZiu3oIDtc3BK5AMxyBXeLhRCQr28Z5gjV7NMSKkgiuTQMspo6AeXZMG/VrZHo85SneyUCvKz7Qd2sDsLLDBw5m20nDIAnfDsin6janYwBXAi4u2uY33zg49Vu8+lq7VcUA/PORjY5aGkdXM8XPrucUWQKijcgm96qDMb5psG4m+wTQbjoDfQW7zalsuFjSJTzPFPkq37YqX1QYHV7cKGZyeWKOXhBstc00QC8Yw/oK8SWaXwx4NKcryiuXQbdlJTSQEJUg7HGg2CkNwdtlF0jPoyU4aE4u12vyVfWj3sbcSEZGJNFIJSy4a9LbtHBcM2CUkpYo2vF4+EO/7ktbfbf8Spjxh65jMUYkkELphKtk40Oym/if8tOLDpZEatn+OK4MFpOTB8EtKoOuRYiAghQG/b3lOONK9Z3hhktVsWcyQERL/UZJXjpoinjIwUcKukfMldoF/1XU4C09UATSbpUFXDFGOhpPmE4f9+5bY6+bKjHuJbIKNfddqMpfjlcmkZYph9i9Wv09AGyUF0gqv4ajAys1wNmUkg1+3xTQcsMRSJbvvt8M+RUojMfoQ8LXhjQxVXfkVfzYobWbknn/Nc25wY0Cc2CO6mnQlsMItIRTWsGKdQFJE5TAQWf3y/7cHWe31Oabp+5USOHIrsgHisXNUPApVk7zJQ9v4Uo2DCgoFA=
  template:
    metadata:
      name: cloudflared-token
      namespace: platform
