---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: unum
spec:
  encryptedData:
    admin-password: AgBkGh30bnvlEYjbv235A+ECqM2zJuu7bOgX969jwx9s9TqnZqCVuYAp9vI3vSx1Phk0oPswxY6SDTaX6+wsMGYGKNV5fxtq90HfAJTjPwY3ZYHftS2mkWqLfdBKOB1IX0ceuSITvlOif6W9vcC6MnPrBtsuBLKfb0oDBmD6szWdypFKILOTmK3iQgRJTtlIyXcOS5MfDnn3SlffrMBURep7TAWOwKIvUnjT+LPX3vT/Dfmj6WK3+XjKxljwoCCBmhAAOik8oPhBYBuuGMDOAxRISFQ/ZNHxIQDsyz9b6kUtZShG/oa5+DBZMlrYXKk6+BRMIJkZyXeV67Kuv0Cz8dGktoo+erkPsOB6/oJl547Yo71V4p2eCdQdrpYztiQVD7gVcfucWywrc3PWO/qCGIszRsfeaFNKE/X/YfJlBB3TMXB1iK3p3sGBW8Qse6zFUN/X/3sDjvM9IHtVK4QB6DH2f8tng57CRWA9347zEIdAZTDEqktt0PdlgEC9QdsXkdIYf+nieP0AIkccC4ChmMFPDL4SPrtwCjj7sryujvGF/GyTSu4cepH9yEvrSW1wK0xZY+OLlZZYDsltLMA08p72dqGNSuJWifFzWkKk2F93KjBEu+jl1tZKTvs0nV2/0JdjhulxiIIAydQonJl66OXZn0A8PDyn8f3WkG7ioZWhzSsYb0b9/CXfgIkKsrr6lJ9f9TmomOdg8G7jZBXg0XsRNQoaXK5nu0oX42KKO7Bw6Nyxvv4c3PqV138=
  template:
    metadata:
      name: grafana-secret
      namespace: unum
