---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: unum
spec:
  encryptedData:
    admin-password: AgBxQ76S3jQniFRqG/D+D6ObH3Js12QMSfOW9biePYDARfjHQomYkYRIMsHl+fhUztqgPl8eqOFDxaiYnZWqal1G8S/Wv+BnoyyLNXcOkvdq5CcShHWT7InFkIhOozAlqX8M9rk1zzQcCVyGpwL3SRINRS/1CiojEnoRZNEXamhuIx5vcBycEvZ1btANU8+QGhFi9wztRMNRPUjXKn6ziddfjxrBet+6/T9kzOHXnCemPjDQyJNNjw4dLcrLjR/6gYmHT82g5gDHMO+9o+SOckzUqHkUx00piwxK36mAVbU96aVqUNARoi+0iu1DMrKRfBgUH0+mFmEKrqbz4MnLC8NwEsoMc0MNT5tFfXjeMmT/QPcOmFAK/IfZpz7GU/tm0XtqHKFnLqCMZ5W2lToDsj8vIb6wQD5Wjv1YCk2HzIWG1TA9FdcekPEJCbLq1bigrErjzlt6TqUadcTcZFz6I9TV3w7hXLwGs6Hb1aUyGEfzqncjED5cX80MXbj6AYJAOjA31U2Yl5HzcrCZ73Ux6HDnRxld+oy7NAeimqxuwDbqt+Y+lEt625hds+CN/1CdMX8hkRzzUw0FH2v/+07hd7w+Pk6VqIyl/eglGECYg13Z1/nL7fXZjzXPetaZSRuxyZ/W2krxjIbpO6WKR3HjoAa6EOSLYZwPOg68KrJFzjCIvL3bTkj7fqPhHZqtnUA8OcGQtDcM8WhkBFPFrm7rCPsZFDXh3vO676o4Gooii6lPY8bUM7CJD/6Z3qs87WI=
  template:
    metadata:
      name: grafana-secret
      namespace: unum
