apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiatlux
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielriddell21/riddellious-dev
    targetRevision: trunk
    path: manifests/fiatlux
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: fiatlux
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
