apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: unum
data:
  config.yaml: |
    tunnel: <TUNNEL_ID>
    credentials-file: /etc/cloudflared/creds.json
    ingress:
      - hostname: hash.unum.tools
        service: http://unum-hash:8080
      - hostname: json.unum.tools
        service: http://unum-json:8080
      - hostname: diff.unum.tools
        service: http://unum-diff:8080
      - service: http_status:404
