apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqld-data
  namespace: fiatlux
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
