---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: otel-collector-secret
  namespace: platform
spec:
  encryptedData:
    auth-token: AgAttamn7zc2IRRXpHO5J20k7y2K4tY9MCiUjCNcyqDKF3ZevRG784crKS0Ucn4VneHTHjA1WbjTZps+r1jhkNU0c1zUeLUIT05gNPx5g1+PnyD8C5ZgWAoa/Mziu0mq85KRbkzJnhL9jkAEsHnv0vGq3AE/0VvLkY1gJMAjGELH4n6IUTMyT/IGjEvt1/H4Ia2ysp+Jp2Gfdh2+ua8n5c325933grxHfMRV0lZlsweLhGgXFKbkD8nSJNYW8G7gOUx/BqUgaKlEkmfGh6o0MvmsP8q3K7PNHZzvGm3mxXcO4G3fowpjssQkA1Zh+Y9lWThyjQyYxr/z8lAwrHLOM5Vqu7rDTOrBvljRwgFFIGPuIYP17dcz6v3b+/0wFVDmWg7S49ANpLPELFAGOi0R8DleCoI0xZMg+PIXQCjeIaQF8T4Nuj/jeXY8fWVLwsSGLO5/6Dw2qsTg3A80LmTPfPaqe8FK43Heuiz+4yXlCgP+zOqL2il0HS7GZo4GXZGkwvxt+BHMknhYAouDOjQ3Ay7QtiSWEZaBn3fJ2R2MMD4uaLIFrDwji+qL0XEwNu/3bpNdyzz+fI2ob/ff3wmMGHpAiWFp0IVgBZ8Zk1Io/+A7PcCuKk3aSwNdr+CPkW02B+VNO8UMTGc7PAdtmqB+JZ84Ju1JyMPXYrs8lzCcg9bhtlblqFqplsUDnI7HZ2215ntWMZ4GOOnhzezZrgDUMGCehZqLnOj8ut5oZdu5idUxuVqUibHDed59e+Ia5BYbGdzdaBIW1EAWHQthM31Ct56F
  template:
    metadata:
      name: otel-collector-secret
      namespace: platform
