apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: platform
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-ext-http
      port: 4318
      targetPort: 4318
    - name: otlp-int-http
      port: 4319
      targetPort: 4319
    - name: otlp-int-grpc
      port: 4317
      targetPort: 4317
    - name: prom-metrics
      port: 8889
      targetPort: 8889
