apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: platform
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
  clusterIP: None  # headless for StatefulSet DNS
