---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: unum
spec:
  encryptedData:
    password: AgCINcp+Ucn9zsdyLjC0C8/u2+VFbF+E8HjpgAnn8SRYPjaxOXazR8uv9e8UJMtiFb6GQsYXwPeJVcqdTeVrD13sXRjKzPImI1RdHjNvl6rFyvFg+Ukp+S2wXBQ6MW5n8bpwic/xv+2DKwgh6w61SADt8x4RWnSdRLkPb7bEPQwnbotC3tOGUDexEyPVvguB4OuNw+Tv1pJ8D6XhAgkNM51Dp6iPaMAD/3GZ53dnHnGm+ghnxos2O4cpgZ+sLwNx8oKl2Vm0zDU3Q3wQ0ZgqdcbqaP5kdfl2ubrgxH6BXxXnht9hedrbM5OdT8wUMGLQTiQo84cyNpuuAugY3+Oq62mRNWuqgGy3OIIkdqyam3g7d/1XShVPmBlCa/us+ynktYMzif/BrTiBj3f3Ja3qB2nspjc7GCyRe7SPzQ8ShXfGHBQ5M/22+mLP4fVy33/O+xrgyhNaJLMFsb5WAj50z/4UTUqPkEwE9teYvMKOtDVbf4OXz9iJW+LQwhRGRKHJ+1PMad+RXMQvLYk8Dy3A/PcBWIx+1XtYR9hWdQRi1tjbi7ddGqanHu0X9OT0z5LIC1odru3L9giu2SqMBqqHqttIzGEmx8reITGaj+H63HYSQy3RHDOP99DGpVeLeyBCQq/MS74tG11kt3ibcvbC7ejUEoJrq/b3LSzemU6r6unlL/dDjinoJOaWPVO/rcN3/99esfSwXop0p1A6Zml9Cct83qaUX8DwKVe85eZtlHJLN5po19fH0Idejayn
  template:
    metadata:
      name: postgres-secret
      namespace: unum
